import { Activity, AlertTriangle, ArrowUpRight, Camera, MapPin, Users } from 'lucide-react'
import AlertItem from '../components/AlertItem'
import CameraTile from '../components/CameraTile'
import StatCard from '../components/StatCard'

const alerts = [{ severity: 'Critical', text: 'Motion detected in restricted zone', time: '14:32:08', sector: 'Sector 04' }, { severity: 'High', text: 'Camera signal lost at BOP Kharpa', time: '14:27:41', sector: 'Sector 02' }, { severity: 'Medium', text: 'Unidentified vehicle approaching', time: '14:19:06', sector: 'Sector 07' }, { severity: 'Medium', text: 'Perimeter sensor triggered', time: '14:04:55', sector: 'Sector 01' }]
const cameras = [{ id: 'CAM-01', location: 'BOP Kharpa / North' }, { id: 'CAM-02', location: 'BOP Kharpa / East' }, { id: 'CAM-03', location: 'Observation Post 07' }, { id: 'CAM-04', location: 'Sector 04 / Perimeter' }]

export default function Dashboard() {
  return <div><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.22em] text-cyan-400"><span className="h-1.5 w-1.5 rounded-full bg-cyan-400" /> Command centre</p><h1 className="font-display text-4xl font-semibold tracking-wide text-white sm:text-5xl">Situation overview</h1><p className="mt-2 text-sm text-slate-500">Live operational status across the border intelligence network.</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><Activity size={15} className="text-emerald-400" /> Updated moments ago</div></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total cameras" value="48" detail="Across 12 border sectors" icon={Camera} /><StatCard label="Active alerts" value="03" detail="1 critical requires attention" icon={AlertTriangle} tone="red" /><StatCard label="Online BOPs" value="12 / 14" detail="85.7% network availability" icon={MapPin} tone="emerald" /><StatCard label="Persons detected today" value="127" detail="+18% from yesterday" icon={Users} tone="amber" /></div><div className="mt-8 grid grid-cols-1 gap-6 xl:grid-cols-[1.55fr_1fr]"><section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-semibold text-white">Camera network</h2><p className="mt-1 text-xs text-slate-600">Selected feeds / Sector North</p></div><button className="flex items-center gap-1 text-xs font-semibold text-cyan-400 hover:text-cyan-300">View all <ArrowUpRight size={14} /></button></div><div className="grid grid-cols-1 gap-3 md:grid-cols-2">{cameras.map((camera) => <CameraTile key={camera.id} {...camera} />)}</div></section><section className="border border-white/[0.07] bg-[#0d1217] px-5"><div className="flex items-center justify-between border-b border-white/[0.07] py-5"><div><h2 className="text-sm font-semibold text-white">Recent alerts</h2><p className="mt-1 text-xs text-slate-600">Latest network events</p></div><span className="rounded bg-red-500/10 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-red-400">3 active</span></div>{alerts.map((alert, index) => <AlertItem key={index} {...alert} />)}<button className="mb-5 mt-2 w-full border border-white/[0.08] py-2.5 text-xs font-semibold text-slate-400 transition hover:border-cyan-400/40 hover:text-cyan-300">Open alert centre</button></section></div></div>
}